import { Card } from "./types";

export const CARDS: Card[] = [
  {
    id: 1,
    price: 50000,
    nb_available: 5,
    star: 5,
    available: "disponible",
    cardTitle: "romuald",
    detailCard: "description",
    relevantStore: "cocody",
    favorite: true,
    promo: true,
    picture: "/assets/images/50000.png",
    created: new Date(),
  },
  {
    id: 2,
    price: 20000,
    nb_available: 5,
    star: 4,
    available: "disponible",
    cardTitle: "romuald",
    detailCard: "description",
    relevantStore: "cocody",
    favorite: true,
    promo: true,
    picture: "/assets/images/20000.png",
    created: new Date(),
  },
  {
    id: 3,
    price: 30000,
    nb_available: 5,
    star: 4,
    available: "disponible",
    cardTitle: "romuald",
    detailCard:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor inviduntLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ",
    relevantStore: "cocody",
    favorite: true,
    promo: true,
    picture: "/assets/images/30000.png",
    created: new Date(),
  },
  {
    id: 4,
    price: 15000,
    nb_available: 50,
    star: 3,
    available: "disponible",
    cardTitle: "romuald",
    detailCard: "description",
    relevantStore: "cocody",
    favorite: true,
    promo: true,
    picture: "/assets/images/15000.png",
    created: new Date(),
  },
  {
    id: 5,
    price: 200000,
    nb_available: 5,
    star: 5,
    available: "disponible",
    cardTitle: "romuald",
    detailCard: "card de 30000",
    relevantStore: "cocody ,sakassou ",
    favorite: true,
    promo: true,
    picture: "/assets/images/200000.png",
    created: new Date(),
  },
  // {
  //     id: 6,
  //     price: 10000,
  //     nb_available: 5,
  //     star: 5,
  //     available:true,
  //     cardTitle:"romuald",
  //     detailCard:"description",
  //     relevantStore:"cocody",
  //     favorite:true,
  //     promo :true,
  //     picture: "/assets/images/50 000@2x.png",
  //     created: new Date()
  // },
  // {
  //     id: 7,
  //     price: 10000,
  //     nb_available: 5,
  //     star: 5,
  //     available:true,
  //     cardTitle:"romuald",
  //     detailCard:"description",
  //     relevantStore:"cocody",
  //     favorite:true,
  //     promo :true,
  //     picture: "/assets/images/100 000@2x.png",
  //     created: new Date()
  // },
  // {
  //     id: 8,
  //     price: 10000,
  //     nb_available: 5,
  //     star: 5,
  //     available:true,
  //     cardTitle:"romuald",
  //     detailCard:"description",
  //     relevantStore:"cocody",
  //     favorite:true,
  //     promo :true,
  //     picture: "/assets/images/200 000@2x.png",
  //     created: new Date()
  // },
];

export const ORDERS = [
  {
    id: 1,
    reference: "CO-GS-00001",
    hour: "13:20",
    date: "20-05-2024",
    amount_total: 5005000,
    infos: [
      {
        number: 200,
        amount: 10000,
      },
      {
        number: 100,
        amount: 30000,
      },
    ],
  },
  {
    id: 2,
    reference: "CO-GS-00002",
    hour: "13:23",
    date: "20-05-2024",
    amount_total: 5005000,
    infos: [
      {
        number: 200,
        amount: 10000,
      },
      {
        number: 100,
        amount: 30000,
      },
    ],
  },
  {
    id: 3,
    reference: "CO-GS-00003",
    hour: "13:26",
    date: "20-05-2024",
    amount_total: 5005000,
    infos: [
      {
        number: 200,
        amount: 10000,
      },
      {
        number: 100,
        amount: 30000,
      },
    ],
  },
  {
    id: 4,
    reference: "CO-GS-00004",
    hour: "13:29",
    date: "20-05-2024",
    amount_total: 5005000,
    infos: [
      {
        number: 200,
        amount: 10000,
      },
      {
        number: 100,
        amount: 30000,
      },
    ],
  },
];
